[package]
name = "twitch-dmenu"
version = "0.1.0"
authors = ["Will Eaton <me@wseaton.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch_api2 = {version = "0.5.0-alpha.5", features=["all", "allow_unknown_fields"]}
twitch_oauth2 = { version = "0.5.0-alpha.5", features=["all"]}
reqwest = "*"
tokio = { version = "1.4.0", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15.0"
surf = "*"
serde_json = "*"